// app/components/tape/CassetteTape.vue
<script setup lang="ts">
import type { Mixtape, Side, Song, CassetteLength } from '~/types';
import '~/assets/styles/CassetteTape.css';

const props = defineProps<{
  mixtape: Mixtape;
  onRemoveSong: (songId: string, side: Side) => void;
  onReorderSongs: (side: Side, songs: Song[]) => void;
  onMoveSong: (songId: string, fromSide: Side, toSide: Side) => void;
  onCassetteLengthChange: (length: CassetteLength) => void;
}>();

const maxDurationPerSide = computed(() => (props.mixtape.cassetteLength / 2) * 60); // in seconds

const handleLengthChange = (e: Event) => {
  props.onCassetteLengthChange(Number((e.target as HTMLSelectElement).value) as CassetteLength);
};
</script>

<template>
  <div class="cassette-container">
    <div class="cassette-controls">
      <label for="cassette-length">Cassette Length:</label>
      <select
        id="cassette-length"
        :value="mixtape.cassetteLength"
        class="cassette-select"
        @change="handleLengthChange"
      >
        <option :value="60">60 min</option>
        <option :value="90">90 min</option>
        <option :value="120">120 min</option>
      </select>
    </div>

    <div class="j-card">
      <TapeSide
        side="A"
        :songs="mixtape.sideA"
        :max-duration="maxDurationPerSide"
        :on-remove-song="onRemoveSong"
        :on-reorder-songs="onReorderSongs"
        :on-move-song="onMoveSong"
      />
      <TapeSide
        side="B"
        :songs="mixtape.sideB"
        :max-duration="maxDurationPerSide"
        :on-remove-song="onRemoveSong"
        :on-reorder-songs="onReorderSongs"
        :on-move-song="onMoveSong"
      />
    </div>
  </div>
</template>

// src/components/tape/CassetteTape.tsx
import { Mixtape, Side, Song, CassetteLength } from '../../types';
import TapeSide from './TapeSide';
import '../../styles/CassetteTape.css';

interface CassetteTapeProps {
  mixtape: Mixtape;
  onRemoveSong: (songId: string, side: Side) => void;
  onReorderSongs: (side: Side, songs: Song[]) => void;
  onMoveSong: (songId: string, fromSide: Side, toSide: Side) => void;
  onCassetteLengthChange: (length: CassetteLength) => void;
}

const CassetteTape = ({
  mixtape,
  onRemoveSong,
  onReorderSongs,
  onMoveSong,
  onCassetteLengthChange,
}: CassetteTapeProps) => {
  const maxDurationPerSide = (mixtape.cassetteLength / 2) * 60; // in seconds

  return (
    <div className="cassette-container">
      <div className="cassette-controls">
        <label htmlFor="cassette-length">Cassette Length:</label>
        <select
          id="cassette-length"
          value={mixtape.cassetteLength}
          onChange={(e) =>
            onCassetteLengthChange(Number(e.target.value) as CassetteLength)
          }
          className="cassette-select"
        >
          <option value={60}>60 min</option>
          <option value={90}>90 min</option>
          <option value={120}>120 min</option>
        </select>
      </div>

      <div className="j-card">
        <TapeSide
          side="A"
          songs={mixtape.sideA}
          maxDuration={maxDurationPerSide}
          onRemoveSong={onRemoveSong}
          onReorderSongs={onReorderSongs}
          onMoveSong={onMoveSong}
        />
        <TapeSide
          side="B"
          songs={mixtape.sideB}
          maxDuration={maxDurationPerSide}
          onRemoveSong={onRemoveSong}
          onReorderSongs={onReorderSongs}
          onMoveSong={onMoveSong}
        />
      </div>
    </div>
  );
};

export default CassetteTape;
