// app/components/spotify/ExportToSpotify.vue
<script setup lang="ts">
import type { Mixtape } from '~/types';
import { isAuthenticated, startSpotifyAuth, clearTokens } from '~/utils/spotifyAuth';
import { exportMixtapeToSpotify, type ExportResult } from '~/utils/spotifyExport';

const props = defineProps<{
  mixtape: Mixtape;
}>();

type State = 'idle' | 'connecting' | 'exporting' | 'success' | 'error';

const connected = ref(import.meta.client ? isAuthenticated() : false);
const state = ref<State>('idle');
const result = ref<ExportResult | null>(null);
const error = ref<string | null>(null);

const handleDisconnect = () => {
  clearTokens();
  connected.value = false;
  state.value = 'idle';
  result.value = null;
};

const handleClick = async () => {
  if (!connected.value) {
    state.value = 'connecting';
    try {
      await startSpotifyAuth();
    } catch {
      state.value = 'error';
      error.value = 'Could not start Spotify login. Check NUXT_PUBLIC_SPOTIFY_CLIENT_ID.';
    }
    return;
  }

  state.value = 'exporting';
  error.value = null;

  try {
    const res = await exportMixtapeToSpotify(props.mixtape);
    result.value = res;
    state.value = 'success';
  } catch (err) {
    error.value = err instanceof Error ? err.message : 'Export failed';
    state.value = 'error';
  }
};

const busy = computed(() => state.value === 'connecting' || state.value === 'exporting');
const label = computed(() =>
  state.value === 'exporting'
    ? 'Exporting...'
    : state.value === 'connecting'
      ? 'Connecting...'
      : connected.value
        ? '⬆ Export to Spotify'
        : 'Connect Spotify'
);
</script>

<template>
  <div class="export-spotify">
    <div v-if="state === 'success' && result" class="export-result">
      <a
        class="btn action-btn export-btn--success"
        :href="result.playlistUrl"
        target="_blank"
        rel="noopener noreferrer"
      >
        Open Playlist ↗
      </a>
      <p v-if="result.skippedCount > 0" class="export-skipped">
        {{ result.addedCount }} added · {{ result.skippedCount }} skipped (not on Spotify)
      </p>
    </div>
    <div v-else-if="state === 'error'" class="export-result">
      <p class="export-error">{{ error }}</p>
      <button class="btn action-btn" @click="state = 'idle'">
        Retry
      </button>
    </div>
    <button v-else class="btn action-btn" :disabled="busy" @click="handleClick">
      {{ label }}
    </button>

    <div class="export-spotify-status">
      <span :class="`export-dot export-dot--${connected ? 'on' : 'off'}`" />
      <span class="export-status-label">
        {{ connected ? 'Spotify linked' : 'Not linked to Spotify' }}
      </span>
      <button v-if="connected" class="export-disconnect" @click="handleDisconnect">
        disconnect
      </button>
    </div>
  </div>
</template>

// src/components/spotify/ExportToSpotify.tsx
import { useState } from 'react';
import { Mixtape } from '../../types';
import { isAuthenticated, startSpotifyAuth, clearTokens } from '../../utils/spotifyAuth';
import { exportMixtapeToSpotify, ExportResult } from '../../utils/spotifyExport';

interface Props {
  mixtape: Mixtape;
}

type State = 'idle' | 'connecting' | 'exporting' | 'success' | 'error';

export default function ExportToSpotify({ mixtape }: Props) {
  const [connected, setConnected] = useState(isAuthenticated);
  const [state, setState] = useState<State>('idle');
  const [result, setResult] = useState<ExportResult | null>(null);
  const [error, setError] = useState<string | null>(null);

  const handleDisconnect = () => {
    clearTokens();
    setConnected(false);
    setState('idle');
    setResult(null);
  };

  const handleClick = async () => {
    if (!connected) {
      setState('connecting');
      try {
        await startSpotifyAuth();
      } catch {
        setState('error');
        setError('Could not start Spotify login. Check VITE_SPOTIFY_CLIENT_ID.');
      }
      return;
    }

    setState('exporting');
    setError(null);

    try {
      const res = await exportMixtapeToSpotify(mixtape);
      setResult(res);
      setState('success');
    } catch (err) {
      setError(err instanceof Error ? err.message : 'Export failed');
      setState('error');
    }
  };

  const busy = state === 'connecting' || state === 'exporting';
  const label = state === 'exporting'
    ? 'Exporting...'
    : state === 'connecting'
    ? 'Connecting...'
    : connected
    ? '⬆ Export to Spotify'
    : 'Connect Spotify';

  return (
    <div className="export-spotify">
      {state === 'success' && result ? (
        <div className="export-result">
          <a
            className="btn action-btn export-btn--success"
            href={result.playlistUrl}
            target="_blank"
            rel="noopener noreferrer"
          >
            Open Playlist ↗
          </a>
          {result.skippedCount > 0 && (
            <p className="export-skipped">
              {result.addedCount} added · {result.skippedCount} skipped (not on Spotify)
            </p>
          )}
        </div>
      ) : state === 'error' ? (
        <div className="export-result">
          <p className="export-error">{error}</p>
          <button className="btn action-btn" onClick={() => setState('idle')}>
            Retry
          </button>
        </div>
      ) : (
        <button className="btn action-btn" onClick={handleClick} disabled={busy}>
          {label}
        </button>
      )}

      <div className="export-spotify-status">
        <span className={`export-dot export-dot--${connected ? 'on' : 'off'}`} />
        <span className="export-status-label">
          {connected ? 'Spotify linked' : 'Not linked to Spotify'}
        </span>
        {connected && (
          <button className="export-disconnect" onClick={handleDisconnect}>
            disconnect
          </button>
        )}
      </div>
    </div>
  );
}
