// src/components/ui/Toast.tsx
import { useEffect } from 'react';
import '../../styles/Toast.css';

interface ToastProps {
  message: string;
  type?: 'success' | 'error' | 'info';
  onClose: () => void;
  duration?: number;
}

export default function Toast({ message, type = 'info', onClose, duration = 3000 }: ToastProps) {
  useEffect(() => {
    const timer = setTimeout(onClose, duration);
    return () => clearTimeout(timer);
  }, [duration, onClose]);

  return (
    <div className={`toast toast-${type}`}>
      {message}
    </div>
  );
}

// app/components/ui/Toast.vue
<script setup lang="ts">
import '~/assets/styles/Toast.css';

const props = withDefaults(
  defineProps<{
    message: string;
    type?: 'success' | 'error' | 'info';
    onClose: () => void;
    duration?: number;
  }>(),
  { type: 'info', duration: 3000 }
);

let timer: ReturnType<typeof setTimeout> | undefined;
onMounted(() => {
  timer = setTimeout(props.onClose, props.duration);
});
onUnmounted(() => clearTimeout(timer));
</script>

<template>
  <div :class="`toast toast-${type}`">
    {{ message }}
  </div>
</template>
