// app/components/jcard/JCardView.vue
<script setup lang="ts">
import { ref, watch } from 'vue';
import { useEventListener } from '@vueuse/core';
import type { JCard, JCardContent, Mixtape } from '~/types';
import { useAuthStore } from '~/stores/auth';
import { useUiStore } from '~/stores/ui';
import { generateId } from '~/utils/timeUtils';
import { buildBlankJCardContent, applyMixtapeToJCard } from '~/utils/jcardDefaults';
import { registerCustomFonts } from '~/utils/fontManager';
import { saveJCardToLocal } from '~/utils/localStorage';
import { loadJCard, createJCard, updateJCard } from '~/utils/jcardDatabase';

const props = defineProps<{
  initialCard: JCard | null;
  currentMixtape: Mixtape | null;
}>();

const auth = useAuthStore();
const ui = useUiStore();

const COALESCE_MS = 600;
const MAX_HISTORY = 20;

function makeBlank(userId: string, mixtape: Mixtape | null): JCard {
  const content = mixtape
    ? applyMixtapeToJCard(buildBlankJCardContent(), mixtape, { overwriteCover: true })
    : buildBlankJCardContent();
  return {
    id: generateId(),
    title: mixtape ? `${mixtape.title} — J-Card` : 'Untitled J-Card',
    userId,
    mixtapeId: mixtape?.id ?? null,
    content,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  };
}

// Seed once.
const seed = props.initialCard ?? makeBlank(auth.user?.id ?? 'local', props.currentMixtape);
const card = ref<JCard>(seed);
const isSaving = ref(false);

// Non-reactive internals (mutating these must NOT trigger a re-render).
let timer: ReturnType<typeof setTimeout> | null = null;
let persisted = !!props.initialCard;
let histStack: JCard[] = [seed];
let histIdx = 0;
let lastPushMs = 0;

const canUndo = ref(false);
const canRedo = ref(false);

// Re-register custom fonts when the card's font list changes.
watch(
  () => card.value.content.customFonts,
  (fonts) => { if (fonts?.length) registerCustomFonts(fonts).catch(console.error); },
  { immediate: true },
);

async function doSave(target: JCard, feedback: boolean) {
  isSaving.value = true;
  saveJCardToLocal(target); // always persist locally first
  try {
    if (auth.user) {
      let saved: JCard;
      if (persisted) {
        saved = await updateJCard(target.id, { title: target.title, content: target.content, mixtapeId: target.mixtapeId ?? null });
      } else {
        const exists = await loadJCard(target.id);
        if (exists) {
          persisted = true;
          saved = await updateJCard(target.id, { title: target.title, content: target.content, mixtapeId: target.mixtapeId ?? null });
        } else {
          saved = await createJCard(auth.user.id, { title: target.title, content: target.content, mixtapeId: target.mixtapeId ?? null });
          persisted = true;
        }
      }
      card.value = { ...card.value, id: saved.id, updatedAt: saved.updatedAt };
    }
    if (feedback) ui.showToast('J-card saved', 'success');
  } catch (e) {
    console.error('Supabase sync failed (card is still saved locally):', e);
    if (feedback) ui.showToast('J-card saved', 'success');
  } finally {
    isSaving.value = false;
  }
}

function schedule(updated: JCard) {
  if (timer) clearTimeout(timer);
  timer = setTimeout(() => doSave(updated, false), 1200);
}

function pushHistory(newCard: JCard) {
  const now = Date.now();
  const base = histStack.slice(0, histIdx + 1);
  let next: JCard[];
  if (now - lastPushMs < COALESCE_MS && base.length > 0) {
    next = [...base.slice(0, -1), newCard];
  } else {
    next = [...base, newCard];
  }
  next = next.slice(-MAX_HISTORY);
  histStack = next;
  histIdx = next.length - 1;
  lastPushMs = now;
  canUndo.value = histIdx > 0;
  canRedo.value = false;
}

function undo() {
  if (histIdx <= 0) return;
  histIdx--;
  lastPushMs = 0;
  const prev = histStack[histIdx];
  card.value = prev;
  schedule(prev);
  canUndo.value = histIdx > 0;
  canRedo.value = true;
}

function redo() {
  if (histIdx >= histStack.length - 1) return;
  histIdx++;
  lastPushMs = 0;
  const nextCard = histStack[histIdx];
  card.value = nextCard;
  schedule(nextCard);
  canUndo.value = true;
  canRedo.value = histIdx < histStack.length - 1;
}

// Keyboard shortcuts — skipped inside a contenteditable so Tiptap keeps its own undo.
useEventListener(typeof document !== 'undefined' ? document : null, 'keydown', (e: KeyboardEvent) => {
  if (!(e.metaKey || e.ctrlKey)) return;
  const active = document.activeElement as HTMLElement | null;
  if (active?.contentEditable === 'true') return;
  if (e.key === 'z' && !e.shiftKey) { e.preventDefault(); undo(); }
  else if (e.key === 'z' && e.shiftKey) { e.preventDefault(); redo(); }
  else if (e.key === 'y') { e.preventDefault(); redo(); }
});

function update(partial: Partial<JCard>) {
  const updated = { ...card.value, ...partial, updatedAt: new Date().toISOString() };
  card.value = updated;
  pushHistory(updated);
  schedule(updated);
}

function saveNow() {
  if (timer) clearTimeout(timer);
  doSave(card.value, true);
}
</script>

<template>
  <div class="jcard-view">
    <!-- Sub-toolbar -->
    <div class="jcard-view-toolbar">
      <h2 class="jcard-view-title">{{ card.title || 'Untitled J-Card' }}</h2>
      <div class="jcard-history-btns">
        <button class="btn" :disabled="!canUndo" title="Undo (⌘Z)" @click="undo">↩</button>
        <button class="btn" :disabled="!canRedo" title="Redo (⌘⇧Z)" @click="redo">↪</button>
      </div>
      <button class="btn btn-primary" :disabled="isSaving" @click="saveNow">
        {{ isSaving ? 'Saving…' : 'Save' }}
      </button>
    </div>

    <!-- 2-column body -->
    <div class="jcard-view-body">
      <div class="jcard-view-main">
        <div class="jcard-view-preview">
          <JCardPreview :content="card.content" label="▧ Outside" />
          <JCardInsidePreview :content="card.content" label="◧ Inside" />
        </div>
      </div>

      <aside class="jcard-view-right">
        <span class="jcard-col-label">⚙ Settings</span>
        <JCardSettings
          :card="card"
          :current-mixtape="currentMixtape"
          :sections="['info', 'presets', 'layout', 'fonts', 'flaps', 'background', 'spine', 'back', 'mixtape', 'export']"
          @title-change="(title: string) => update({ title })"
          @content-change="(content: JCardContent) => update({ content })"
          @mixtape-link="(mixtapeId: string | null) => update({ mixtapeId })"
        />
      </aside>
    </div>
  </div>
</template>

// src/components/jcard/JCardView.tsx
import { useState, useRef, useCallback, useEffect, useMemo } from 'react';
import { JCard, JCardContent, Mixtape } from '../../types';
import { buildBlankJCardContent, applyMixtapeToJCard } from '../../utils/jcardDefaults';
import { generateId } from '../../utils/timeUtils';
import { saveJCardToLocal } from '../../utils/localStorage';
import { createJCard, updateJCard, loadJCard } from '../../utils/jcardDatabase';
import { useAuth } from '../../contexts/AuthContext';
import { registerCustomFonts } from '../../utils/fontManager';
import JCardPreview from './JCardPreview';
import JCardSettings from './JCardSettings';
import '../../styles/jcard/JCardView.css';

interface Props {
  initialCard: JCard | null;
  currentMixtape: Mixtape | null;
  onBack: () => void;
  showToast: (msg: string, type: 'success' | 'error' | 'info') => void;
}

function makeBlank(userId: string, mixtape: Mixtape | null): JCard {
  const content = mixtape
    ? applyMixtapeToJCard(buildBlankJCardContent(), mixtape, { overwriteCover: true })
    : buildBlankJCardContent();
  return {
    id: generateId(),
    title: mixtape ? `${mixtape.title} — J-Card` : 'Untitled J-Card',
    userId,
    mixtapeId: mixtape?.id ?? null,
    content,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  };
}

// ─── History helpers ────────────────────────────────────────────────────────
const COALESCE_MS = 600;
const MAX_HISTORY = 20;

// ────────────────────────────────────────────────────────────────────────────

const JCardView = ({ initialCard, currentMixtape, onBack: _onBack, showToast }: Props) => {
  const { user } = useAuth();
  const seed = useMemo(() => initialCard ?? makeBlank(user?.id ?? 'local', currentMixtape), []); // eslint-disable-line react-hooks/exhaustive-deps
  const [card, setCard] = useState<JCard>(seed);
  const [isSaving, setIsSaving] = useState(false);
  const timer = useRef<ReturnType<typeof setTimeout> | null>(null);
  const persisted = useRef(!!initialCard);

  // ── Undo / redo stack (refs → no spurious re-renders for stack internals) ──
  const histStack = useRef<JCard[]>([seed]);
  const histIdx   = useRef(0);
  const lastPushMs = useRef(0);
  const [canUndo, setCanUndo] = useState(false);
  const [canRedo, setCanRedo] = useState(false);

  // Re-register custom fonts whenever the card's font list changes so the
  // preview and editors always have them available (e.g. after opening an
  // existing card that has stored fonts).
  useEffect(() => {
    const fonts = card.content.customFonts;
    if (fonts?.length) registerCustomFonts(fonts).catch(console.error);
  }, [card.content.customFonts]);

  const doSave = useCallback(async (target: JCard, feedback: boolean) => {
    setIsSaving(true);
    // Always persist to localStorage first — this guarantees the card is never lost.
    saveJCardToLocal(target);
    try {
      if (user) {
        // Also sync to Supabase when logged in.
        let saved: JCard;
        if (persisted.current) {
          saved = await updateJCard(target.id, { title: target.title, content: target.content, mixtapeId: target.mixtapeId ?? null });
        } else {
          const exists = await loadJCard(target.id);
          if (exists) {
            persisted.current = true;
            saved = await updateJCard(target.id, { title: target.title, content: target.content, mixtapeId: target.mixtapeId ?? null });
          } else {
            saved = await createJCard(user.id, { title: target.title, content: target.content, mixtapeId: target.mixtapeId ?? null });
            persisted.current = true;
          }
        }
        setCard(prev => ({ ...prev, id: saved.id, updatedAt: saved.updatedAt }));
      }
      if (feedback) showToast('J-card saved', 'success');
    } catch (e) {
      console.error('Supabase sync failed (card is still saved locally):', e);
      // Don't show an error — card is safely in localStorage.
      if (feedback) showToast('J-card saved', 'success');
    } finally { setIsSaving(false); }
  }, [user, showToast]);

  const schedule = useCallback((updated: JCard) => {
    if (timer.current) clearTimeout(timer.current);
    timer.current = setTimeout(() => doSave(updated, false), 1200);
  }, [doSave]);

  // ── History mutations ──────────────────────────────────────────────────────
  const pushHistory = useCallback((newCard: JCard) => {
    const now = Date.now();
    const base = histStack.current.slice(0, histIdx.current + 1);
    let next: JCard[];
    if (now - lastPushMs.current < COALESCE_MS && base.length > 0) {
      // Coalesce rapid edits: replace the current tip instead of adding a new entry.
      next = [...base.slice(0, -1), newCard];
    } else {
      next = [...base, newCard];
    }
    next = next.slice(-MAX_HISTORY);
    histStack.current = next;
    histIdx.current   = next.length - 1;
    lastPushMs.current = now;
    setCanUndo(histIdx.current > 0);
    setCanRedo(false);
  }, []);

  const undo = useCallback(() => {
    if (histIdx.current <= 0) return;
    histIdx.current--;
    lastPushMs.current = 0; // break coalescing after navigation
    const prev = histStack.current[histIdx.current];
    setCard(prev);
    schedule(prev);
    setCanUndo(histIdx.current > 0);
    setCanRedo(true);
  }, [schedule]);

  const redo = useCallback(() => {
    if (histIdx.current >= histStack.current.length - 1) return;
    histIdx.current++;
    lastPushMs.current = 0;
    const next = histStack.current[histIdx.current];
    setCard(next);
    schedule(next);
    setCanUndo(true);
    setCanRedo(histIdx.current < histStack.current.length - 1);
  }, [schedule]);

  // Keyboard shortcuts — Cmd/Ctrl+Z and Cmd/Ctrl+Shift+Z.
  // Skipped when focus is inside a contenteditable so Tiptap's own
  // per-editor undo still works for fine-grained text edits.
  useEffect(() => {
    const handler = (e: KeyboardEvent) => {
      if (!(e.metaKey || e.ctrlKey)) return;
      const active = document.activeElement as HTMLElement | null;
      if (active?.contentEditable === 'true') return; // let Tiptap handle it
      if (e.key === 'z' && !e.shiftKey) { e.preventDefault(); undo(); }
      else if (e.key === 'z' &&  e.shiftKey) { e.preventDefault(); redo(); }
      else if (e.key === 'y') { e.preventDefault(); redo(); }
    };
    document.addEventListener('keydown', handler);
    return () => document.removeEventListener('keydown', handler);
  }, [undo, redo]);

  const update = (partial: Partial<JCard>) => {
    const updated = { ...card, ...partial, updatedAt: new Date().toISOString() };
    setCard(updated);
    pushHistory(updated);
    schedule(updated);
  };

  const saveNow = () => { if (timer.current) clearTimeout(timer.current); doSave(card, true); };

  return (
    <div className="jcard-view">

      {/* Sub-toolbar */}
      <div className="jcard-view-toolbar">
        <h2 className="jcard-view-title">{card.title || 'Untitled J-Card'}</h2>
        <div className="jcard-history-btns">
          <button className="btn" onClick={undo} disabled={!canUndo} title="Undo (⌘Z)">↩</button>
          <button className="btn" onClick={redo} disabled={!canRedo} title="Redo (⌘⇧Z)">↪</button>
        </div>
        <button className="btn btn-primary" onClick={saveNow} disabled={isSaving}>
          {isSaving ? 'Saving…' : '💾 Save'}
        </button>
      </div>

      {/* 2-column body */}
      <div className="jcard-view-body">

        {/* MAIN — preview */}
        <div className="jcard-view-main">
          <div className="jcard-view-preview">
            <span className="jcard-col-label">▧ Live preview</span>
            <JCardPreview content={card.content} />
          </div>
        </div>

        {/* RIGHT — all settings + content */}
        <aside className="jcard-view-right">
          <span className="jcard-col-label">⚙ Settings</span>
          <JCardSettings
            card={card}
            currentMixtape={currentMixtape}
            onTitleChange={(title) => update({ title })}
            onContentChange={(content: JCardContent) => update({ content })}
            onMixtapeLink={(mixtapeId) => update({ mixtapeId })}
            sections={['info', 'presets', 'layout', 'fonts', 'flaps', 'background', 'spine', 'back', 'inside', 'mixtape', 'export']}
          />
        </aside>

      </div>

    </div>
  );
};

export default JCardView;
